create database OlympicGamesDB; 
GO
use OlympicGamesDB;
GO
create table Countries
(
	id int not null unique identity, primary key(id),
	Name varchar(50) not null
);
GO
create table Towns
(
	id int not null unique identity, primary key(id),
	Name varchar(50) not null, 
	CountryId int not null, foreign key(CountryId) references Countries(id)
);
GO
create table Sports
(
	id int not null unique identity, primary key(id),
	Name varchar(30) not null
);
GO
create table Coaches
(
	id int not null identity, primary key(id),
	Name varchar(50) not null,
	SportId int not null, foreign key(SportId) references Sports(id)
);
GO
create table Competitors
(
	id int not null unique identity, primary key(id),
	FullName varchar(50) not null,
	BirthDate date not null,
	Age int not null, 
	Gender char not null,
	Weight int not null,
	TownId int , foreign key(TownId) references Towns(id),
	CoachId int , foreign key(CoachId) references Coaches(id),	
	SportId int not null, foreign key(SportId) references Sports(id),
);
GO
create table Clubs
(
	id int not null identity, primary key(id),
	Name varchar(50) not null
);
GO
INSERT INTO Sports
  (Name)
VALUES
  ('Archery'),
  ('Artistic Swimming'),
  ('Athletics'),
  ('Badminton'),
  ('Baseball And Softball'),
  ('Basketball'),
  ('Beach Volleyball'),
  ('Boxing'),
  ('Canoe Slalom'),
  ('Canoe Sprint'),
  ('Cycling Bmx'),
  ('Cycling Mountain Bike'),
  ('Cycling Road'),
  ('Cycling Track'),
  ('Diving'),
  ('Equestrian/Dressage'),
  ('Equestrian/Eventing'),
  ('Equestrian/Jumping'),
  ('Fencing'),
  ('Football'),
  ('Golf'),
  ('Gymnastics Artistic'),
  ('Gymnastics Rhythmic'),
  ('Handball'),
  ('Hockey'),
  ('Judo'),
  ('Karate'),
  ('Marathon Swimming'),
  ('Modern Pentathlon'),
  ('Rowing'),
  ('Rugby'),
  ('Sailing'),
  ('Shooting'),
  ('Skateboarding'),
  ('Sport Climbing'),
  ('Surfing'),
  ('Swimming'),
  ('Table Tennis'),
  ('Taekwondo'),
  ('Tennis'),
  ('Trampoline'),
  ('Triathlon'),
  ('Volleyball'),
  ('Water Polo'),
  ('Weightlifting'),
  ('Wrestling Freestyle'),
  ('Wrestling Greco-Roman');
GO
INSERT INTO Clubs
  (Name)
VALUES
  ('Aeon'),
  ('AK Nikšić'),
  ('Aliya Yusupova School'),
  ('Andong National University'),
  ('Angolan Swimming Federation'),
  ('Ankara İller Bankası'),
  ('ANSR'),
  ('Armed Forces of Ukraine'),
  ('ASC Dukla'),
  ('Aski Spor Kulübü'),
  ('ASM Clermont Auvergne'),
  ('Association Sportive de Bourgla Reine'),
  ('Athanasia Gymnastics Club'),
  ('Bahrains Swedish medley relay team.'),
  ('Bekasi Regency'),
  ('Benfica'),
  ('Bergen Triathlon Club'),
  ('Bosnia and Herzegovina Davis Cup team'),
  ('Buckeye Gymnastics'),
  ('Budokan Rotterdam'),
  ('Burtases'),
  ('C.D. Promete'),
  ('C.S. Esercito'),
  ('Canadian national modern pentathlon team'),
  ('CASI'),
  ('CB Atlético Guardés'),
  ('CCC Team'),
  ('Cedevita'),
  ('Cerro Pelado'),
  ('Champion Shooting Club'),
  ('Chisinau Zirve'),
  ('Chongqing'),
  ('CKA'),
  ('Club Atlético San Sebastián'),
  ('Club Egara'),
  ('Club Sportif Sfaxien'),
  ('CSA Steaua'),
  ('CSA Steaua București'),
  ('Dynamo'),
  ('Dynamo Tashkent'),
  ('Espérance ST'),
  ('Excalibur Gymnastics'),
  ('FC Köln'),
  ('Ferencvárosi TC'),
  ('Fiji'),
  ('Florida International University'),
  ('Floyds Pro Cycling'),
  ('Futuro'),
  ('GOG'),
  ('GS Petroliers'),
  ('Guadalajara'),
  ('Hansons-Brooks ODP'),
  ('Hapoel Tel Aviv'),
  ('HBV Ontspanning'),
  ('Hermanos Varela'),
  ('Hirnyk Sports Club'),
  ('Iksan City Government Fencing Club'),
  ('Instituto Reação'),
  ('International Boxing Association'),
  ('International team'),
  ('Iowa Hawkeyes'),
  ('Johns Hopkins University'),
  ('Jos Feron Lady Force'),
  ('Judo klub Z’ dežele Sankaku Celje'),
  ('Kenya'),
  ('Khilchin'),
  ('Kigwancha Sports Club'),
  ('Kopparbergs/Göteborg FC'),
  ('KTW Kalisz'),
  ('Latvian Olympic Team'),
  ('Levallois Sporting Club'),
  ('LFB'),
  ('Lithuania national basketball team'),
  ('Liu Jo Nordmeccanica Modena'),
  ('Lokomotiva'),
  ('Longhorn Aquatics'),
  ('LSU Tigers'),
  ('Majlis Sukan Negara'),
  ('Mannheimer HC'),
  ('Marseille Mazargues Canoe Kayak'),
  ('Meitav Jerusalem'),
  ('Melbourne Vicentre'),
  ('Melrose RFC'),
  ('Miyukigahara SS'),
  ('Miyukigahara SS'),
  ('Modena Volley'),
  ('MVP Track Club'),
  ('National team'),
  ('Oulun Jousimiehet'),
  ('Paris Saint-Germain'),
  ('Pärnu Sõudeklubi'),
  ('Poona Golf Club'),
  ('Pure Athletics Club'),
  ('Pyongyang Sports Club'),
  ('Racers Track Club'),
  ('Reading Royals'),
  ('Red Rock'),
  ('RFCL'),
  ('Rio Yacht Club'),
  ('Rostov-Don'),
  ('RTW Lotto Bydgostia'),
  ('Ruvshsm'),
  ('Ryukyu Asteeda'),
  ('S.L. Benfica'),
  ('ŠCP Bratislava'),
  ('Sduschor 1'),
  ('Seeclub-Luzern'),
  ('Shandong Weiqiao'),
  ('Sigma Nordsjælland'),
  ('South Africa Sevens'),
  ('Stade Sottevillais 76'),
  ('Sunkist Kids'),
  ('Swiss National Team'),
  ('Te Stela Swimming Club'),
  ('Texas Longhorns swimming team'),
  ('Tianyoude Hotel Cycling Team'),
  ('Tijuana'),
  ('Tirana Delfina Sport'),
  ('Trojan Swim Club'),
  ('TSS Aquatic'),
  ('TSV Schmiden'),
  ('Udinese'),
  ('Universidad de Chile'),
  ('Universidad Nacional Evangélica'),
  ('University of California'),
  ('US water polo team'),
  ('VBC Chamalières'),
  ('Vipers Kristiansand'),
  ('West End Rowing Club'),
  ('West Virginia Mountaineers'),
  ('World Cycling Centre'),
  ('Worthing Archery Club (GBR)'),
  ('Yacht Club Punta del Este');
GO
INSERT INTO Coaches
  (Name,SportId)
VALUES
  ('Park Chae-soon',1),
  ('Gary Kinghorn',1),
  ('Lance Brauman',3),
  ('Marc Corstjens',3),
  ('Roger Lespagnard',3),
  ('Stephen Francis',3),
  ('Glen Mills',3),
  ('Claudio Beradelli',3),
  ('Kevin Hanson',3),
  ('Kader-Sofiane MIS',3),
  ('Drago Music',3),
  ('Anna "Tannie Ans" Botha',3),
  ('Wang Chen',4),
  ('Richard Mainaky',4),
  ('Cheah Soon Kit',4),
  ('António Leite',4),
  ('Lee Kyung-won',4),
  ('Fernando Rivas',4),
  ('Aleksandar Petrović',6),
  ('Ron van der Hoff',7),
  ('Ydol Alfredo Gonzalez',8),
  ('Albert Tobelem',9),
  ('Genadijs Zujevs',10),
  ('Mykola Matsapura',10),
  ('Jim Ochowicz',13),
  ('Zhang Yukun',15),
  ('Hugues Obry',19),
  ('Gheorghe Epurescu',19),
  ('Lee Soo-geun',19),
  ('Yann Detienne',19),
  ('Artem Skorokhod',19),
  ('Thomas Tuchel',20),
  ('Markus Gisdol',20),
  ('Panagiotis Petridis',22),
  ('Kim Chun-phil',22),
  ('Gustavo Moure',22),
  ('Anatoly Zabelin',22),
  ('Gennady Sartynsky',22),
  ('Christian Gallardo',22),
  ('Melissa Kutcher',22),
  ('Olga Vlasova',23),
  ('Galina Krylenko',23),
  ('Dimitris Raftis',23),
  ('Oka Kurumi',23),
  ('Aliya Yussupova',23),
  ('Maria Girba',23),
  ('Sevara Karimova',23),
  (' Nicklas Beneck',25),
  ('Geraldo Bernardes',26),
  ('Gill Offer',26),
  ('Kosei Inoue',26),
  ('Mark van der Ham',26),
  ('Marjan Fabjan',26),
  ('Vasile Colta',26),
  ('Octavio Angelito',29),
  ('Alexei Khaplanov',29),
  ('Rachel Davis',30),
  ('S Johnson',31),
  ('Javier Torres del Moral',32),
  ('Gal Friedman',32),
  ('Undralbat Lkhagva',33),
  ('Park Chung Gun',33),
  ('Shpetim Hoxha',37),
  ('Chris Nesbitt',37),
  ('Craig Jackson',37),
  ('Shannon Rollason',37),
  ('Vladimir Rybchenko',37),
  ('Vančo Stojanov',37),
  ('Dave Salo',37),
  ('Dave Durden',37),
  ('Dean Price',37),
  ('Miguel Camacho',39),
  ('Rossindo Alonso',39),
  ('Cüneyt Gülçek',39),
  ('Damir Bašić, Daniel Meyers',40),
  ('Radek Stepanek ',40),
  ('Jiří Vaněk ',40),
  ('Jamie Delgado',40),
  ('Svetko Bjelotomić',40),
  ('Philippe DeHaes',40),
  ('Milan Martinec',40),
  ('Klaudiya Istomina',40),
  ('Valery Murtazin',41),
  ('Elena Fedorenchic',41),
  ('Jean-René Akono',43),
  ('Ricardo Azevedo',44),
  ('Jaiber Manjarres',45),
  ('Khaled Korani',45),
  ('Gheorghe Gutu',45),
  ('Rodolphe Kreutzer',46),
  ('Abdullah Çakmak',46),
  ('Valentin Kalika',46),
  ('Hakim Makhmudov',47),
  ('Nichol Berberou',47),
  ('Olimjon Kurbanov',47);
GO
INSERT INTO Countries
  (Name)
VALUES
  ('Albania'),
  ('Algeria'),
  ('Angola'),
  ('Argentina'),
  ('Armenia'),
  ('Australia'),
  ('Austria'),
  ('Azerbaijan'),
  ('Bahamas'),
  ('Bahrain'),
  ('Bangladesh'),
  ('Barbados'),
  ('Belarus'),
  ('Belgium'),
  ('Bolivia'),
  ('Bosnia and Herzegovina'),
  ('Botswana'),
  ('Brazil'),
  ('Bulgaria'),
  ('Cameroon'),
  ('Canada'),
  ('Chile'),
  ('China'),
  ('Chinese Taipei'),
  ('Colombia'),
  ('Croatia'),
  ('Cuba'),
  ('Cyprus'),
  ('Czech Republic'),
  ('Denmark'),
  ('Dominican Republic'),
  ('Ecuador'),
  ('Egypt'),
  ('Eritrea'),
  ('Estonia'),
  ('Ethiopia'),
  ('Fiji'),
  ('Finland'),
  ('France'),
  ('Georgia'),
  ('Germany'),
  ('Great Britain'),
  ('Greece'),
  ('Hong Kong'),
  ('Indonesia'),
  ('Iran'),
  ('Iraq'),
  ('Israel'),
  ('Italy'),
  ('Jamaica'),
  ('Japan'),
  ('Kazakhstan'),
  ('Kenya'),
  ('Kyrgyzstan'),
  ('Latvia'),
  ('Libya'),
  ('Lithuania'),
  ('Luxembourg'),
  ('Macedonia'),
  ('Madagascar'),
  ('Malaysia'),
  ('Mexico'),
  ('Moldova'),
  ('Mongolia'),
  ('Montenegro'),
  ('Morocco'),
  ('Netherlands'),
  ('New Zealand'),
  ('Nigeria'),
  ('North Korea'),
  ('Norway'),
  ('Peru'),
  ('Poland'),
  ('Portugal'),
  ('Puerto Rico'),
  ('Qatar'),
  ('Romania'),
  ('Russia'),
  ('Senegal'),
  ('Serbia'),
  ('Singapore'),
  ('Slovakia'),
  ('Slovenia'),
  ('South Africa'),
  ('South Korea'),
  ('Spain'),
  ('Sweden'),
  ('Switzerland'),
  ('Syria'),
  ('Thailand'),
  ('Trinidad and Tobago'),
  ('Tunisia'),
  ('Turkey'),
  ('Uganda'),
  ('Ukraine'),
  ('United Arab Emirates'),
  ('United States'),
  ('Uruguay'),
  ('Uzbekistan'),
  ('Venezuela'),
  ('Vietnam'),
  ('Zimbabwe');

INSERT INTO Towns
  (Name,CountryId)
VALUES
  ('Al-Huaniya',1),
  ('Almada',1),
  ('Almaty',2),
  ('Anshan',3),
  ('Bắc Giang',4),
  ('Baghdad',4),
  ('Bandung',5),
  ('Bangkok',5),
  ('Banyumas',6),
  ('Baruunturuun',6),
  ('Barysaw',6),
  ('Bau',7),
  ('Bayaguana',8),
  ('Beijing',8),
  ('Bekabad',9),
  ('Berlin',9),
  ('Betsihaka',10),
  ('Bílovec',11),
  ('Boumerdès',11),
  ('Bratislava',12),
  ('Bridgetown',13),
  ('Brussels',13),
  ('Bucharest',14),
  ('Buenos Aires',14),
  ('Bukhara',15),
  ('Bülach',16),
  ('Bulawayo',16),
  ('Busan',17),
  ('Cairo',18),
  ('Caledon East',18),
  ('California',18),
  ('Cambridge, Massachusetts',18),
  ('Cape Town',19),
  ('Caracas',19),
  ('Cardiff',20),
  ('Celje',20),
  ('Cetinje',21),
  ('Chiba Prefecture',21),
  ('Chongqing',22),
  ('Clermont Ferrand',23),
  ('Cologne',23),
  ('Cuautla',24),
  ('Cuenca',25),
  ('Cumaná',25),
  ('Debarwa',26),
  ('Dhaka',26),
  ('Doha',27),
  ('Donetsk',27),
  ('Douala',28),
  ('Drama',29),
  ('Dunedin',29),
  ('Eleutheria',30),
  ('Faiyum',30),
  ('Fier',31),
  ('Florence',31),
  ('Gaborone',32),
  ('Galoya',33),
  ('Glasgow',33),
  ('Gochang-gun',33),
  ('Gori',34),
  ('Gothenburg',35),
  ('Haarlem',36),
  ('Hanoi',36),
  ('Harare',37),
  ('Hartford',38),
  ('Haskovo',38),
  ('Haykashen',39),
  ('Heeswijk-Dinther',39),
  ('Heinävesi',40),
  ('Herlev',41),
  ('Herzliya',41),
  ('Hong Kong',41),
  ('Huelva',42),
  ('Iganga',42),
  ('Imizu',42),
  ('Jeldu',43),
  ('Jerusalem',44),
  ('Kalisz',45),
  ('Karaj',45),
  ('Kaunas',46),
  ('Kermanshah',46),
  ('Khmelnytskyi',47),
  ('Kishinev',48),
  ('Korotogo',48),
  ('Kraaifontein',49),
  ('Lasarte-Oria',49),
  ('Lima',50),
  ('Limassol',50),
  ('Logroño',51),
  ('Lokeren',51),
  ('Lucerne',51),
  ('Lunbei',51),
  ('Luxembourg',52),
  ('Lviv',52),
  ('Manama',53),
  ('Manchester',53),
  ('Mansfield',54),
  ('Marseille',55),
  ('Maryland',55),
  ('Matehuala',56),
  ('Maturín',57),
  ('Medellín',57),
  ('Shanghai',58),
  ('Melbourne',59),
  ('Melrose',60),
  ('Mérida',61),
  ('Miyazaki',61),
  ('Mogi das Cruzes',62),
  ('Montevideo',62),
  ('Mostar',62),
  ('Muar',63),
  ('Murcia',64),
  ('Mykolaiv',64),
  ('Naarden',65),
  ('Nam Định',65),
  ('Nandi District',66),
  ('Narali',66),
  ('Nassau',67),
  ('Naugatuck',67),
  ('New South Wales',68),
  ('New York',68),
  ('Nikšić',69),
  ('Niterói',70),
  ('Novi Sad',70),
  ('Novo Konjarevo',71),
  ('Nyköping',72),
  ('Omsk',73),
  ('Orenburg',73),
  ('Oyama',74),
  ('Pamplona',74),
  ('Pãrnu',74),
  ('Pathum Thani Province',75),
  ('Penza',76),
  ('Pianar del Río',76),
  ('Plovdiv',76),
  ('Pointe-à-Pitre',77),
  ('Ponte de Lima',77),
  ('Portimão',78),
  ('Porto',78),
  ('Potoka',78),
  ('Prague',78),
  ('Puerto Ordaz',79),
  ('Pyongyang',80),
  ('Qatar',80),
  ('Raahe',81),
  ('Reading',82),
  ('Rīga',83),
  ('Rijeka',84),
  ('Rio de Janeiro',85),
  ('Riyadh',85),
  ('Rome',85),
  ('San Juan',86),
  ('Santiago',86),
  ('Santiago de Cuba',86),
  ('Santo Dominigo',86),
  ('Sarajevo',86),
  ('Shanghai',86),
  ('Sherwood Content',87),
  ('Shkoder',87),
  ('Shymkent',87),
  ('Singapore',88),
  ('Sivas',88),
  ('Skien',89),
  ('Søborg',90),
  ('South Hamgyong',90),
  ('Soviet Union',91),
  ('Spilit',92),
  ('St. Gallen',93),
  ('Stockholm',93),
  ('Sucre',93),
  ('Talas',94),
  ('Tashkent',95),
  ('Tashkent Region',95),
  ('Terrassa',96),
  ('Tianjin',96),
  ('Toco',97),
  ('Tolyatti',97),
  ('Toronto',97),
  ('Tunis',97),
  ('Turkmenistan',97),
  ('Ukhul',98),
  ('Ulaanbaatar',98),
  ('Valmiera',99),
  ('Van',99),
  ('Vihiga',99),
  ('Vilnius',99),
  ('Virginia',99),
  ('Vitebsk',100),
  ('Volgograd',100),
  ('Wąbrzeźno',100),
  ('Washington',100),
  ('Wenbera',100),
  ('Wettingen',101),
  ('Yaoundé',101),
  ('Ystad',101),
  ('Zaragoza',102),
  ('Zrenjanin',102);



